apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: peaks-hikes-service
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: peaks-hikes-service
      context: .
      docker:
        dockerfile: Dockerfile
    - image: peaks-hikes-service-migrator
      context: .
      docker:
        dockerfile: Dockerfile.migrator
deploy:
  helm:
    releases:
      - name: peaks-hikes-service
        chartPath: helm
        namespace: dev
        createNamespace: true
        valuesFiles:
          - helm/values-dev.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_peaks_hikes_service}}"
          image.tag: "{{.IMAGE_TAG_peaks_hikes_service}}"
          flyway.image.repository: "{{.IMAGE_REPO_peaks_hikes_service_migrator}}"
          flyway.image.tag: "{{.IMAGE_TAG_peaks_hikes_service_migrator}}"
        wait: true
portForward:
  - resourceType: service
    resourceName: peaks-hikes-service-nodeport
    namespace: dev
    port: 8082
    localPort: 8082
profiles:
  - name: minikube
    activation:
      - kubeContext: minikube