CREATE SCHEMA IF NOT EXISTS peaks_hikes_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA peaks_hikes_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA peaks_hikes_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;
